services:
  proxima:
    image: jeonhui/proxima:latest
    container_name: proxima
    restart: unless-stopped
    pid: host
    ports:
      - "20222:20222"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pxm-data:/data
      - pxm-stacks:/data/stacks
    networks:
      - pxm-network

networks:
  pxm-network:
    name: pxm-network

volumes:
  pxm-data:
  pxm-stacks:
